import Foundation
import os

// MARK: - Generated Metadata Value Types

/// A chapter marker generated by the LLM.
public struct GeneratedChapter: Codable, Sendable, Equatable {
    /// Short chapter title.
    public var title: String
    /// Start time in seconds.
    public var startTime: Double
    /// End time in seconds.
    public var endTime: Double

    public init(title: String, startTime: Double, endTime: Double) {
        self.title = title
        self.startTime = startTime
        self.endTime = endTime
    }
}

/// Social media blurbs generated by the LLM.
public struct GeneratedBlurbs: Codable, Sendable, Equatable {
    /// Tweet-length blurb (max 280 characters).
    public var twitter: String
    /// Professional LinkedIn post.
    public var linkedin: String
    /// Mastodon post (max 500 characters).
    public var mastodon: String

    public init(twitter: String, linkedin: String, mastodon: String) {
        self.twitter = twitter
        self.linkedin = linkedin
        self.mastodon = mastodon
    }
}

/// Episode metadata fields generated from a transcript by the LLM.
///
/// This is a pure value type — the UI layer is responsible for applying
/// these values to the SwiftData ``Episode`` model.
public struct GeneratedMetadata: Codable, Sendable, Equatable {
    /// Suggested episode title.
    public var title: String
    /// Suggested subtitle.
    public var subtitle: String
    /// HTML description for podcast directories.
    public var descriptionHTML: String
    /// Chapter markers with timestamps.
    public var chapters: [GeneratedChapter]
    /// Relevant keywords.
    public var keywords: [String]
    /// Social media promotional blurbs.
    public var blurbs: GeneratedBlurbs

    public init(
        title: String,
        subtitle: String,
        descriptionHTML: String,
        chapters: [GeneratedChapter],
        keywords: [String],
        blurbs: GeneratedBlurbs
    ) {
        self.title = title
        self.subtitle = subtitle
        self.descriptionHTML = descriptionHTML
        self.chapters = chapters
        self.keywords = keywords
        self.blurbs = blurbs
    }
}

// MARK: - Internal Codable Shapes

/// JSON shape returned by the episode-metadata prompt.
private struct MetadataJSON: Codable, Sendable {
    var title: String
    var subtitle: String
    var description: String
    var keywords: [String]
}

// MARK: - Service

/// Generates episode metadata (title, description, chapters, keywords, blurbs)
/// from a transcript using an ``LLMService``.
///
/// Returns a ``GeneratedMetadata`` value type — does **not** mutate SwiftData models.
public struct MetadataGenerationService: Sendable {

    private let llmService: LLMService
    private let logger = PodedgeLogger.llm

    /// Creates a metadata generation service.
    ///
    /// - Parameter llmService: The LLM service used to run prompt completions.
    public init(llmService: LLMService) {
        self.llmService = llmService
    }

    /// Generates full episode metadata from a transcript.
    ///
    /// Runs three LLM calls (metadata, chapters, blurbs) and assembles the results.
    ///
    /// - Parameters:
    ///   - transcript: The plain-text transcript of the episode.
    ///   - showTitle: The name of the podcast show.
    ///   - episodeNumber: The episode number as a string (e.g. `"42"`).
    /// - Returns: A ``GeneratedMetadata`` value with all generated fields.
    /// - Throws: ``PodedgeError/llmFailed(reason:)`` on failure.
    public func generate(
        transcript: String,
        showTitle: String,
        episodeNumber: String
    ) async throws -> GeneratedMetadata {
        let variables: [String: String] = [
            "transcript": transcript,
            "show_title": showTitle,
            "episode_number": episodeNumber,
        ]

        logger.info("Generating metadata for '\(showTitle, privacy: .public)' ep \(episodeNumber, privacy: .public)")

        // Run metadata + chapters + blurbs concurrently.
        async let metadataResponse = llmService.complete(
            promptName: "episode-metadata",
            variables: variables,
            schema: Self.metadataSchema
        )
        async let chaptersResponse = llmService.complete(
            promptName: "chapters",
            variables: variables,
            schema: Self.chaptersSchema
        )
        async let blurbsResponse = llmService.complete(
            promptName: "social-blurbs",
            variables: variables,
            schema: Self.blurbsSchema
        )

        let (metaResp, chapResp, blurbResp) = try await (metadataResponse, chaptersResponse, blurbsResponse)

        let decoder = JSONDecoder()

        let meta = try decodeOrThrow(MetadataJSON.self, from: metaResp.text, using: decoder, label: "metadata")
        let chapters = try decodeOrThrow([GeneratedChapter].self, from: chapResp.text, using: decoder, label: "chapters")
        let blurbs = try decodeOrThrow(GeneratedBlurbs.self, from: blurbResp.text, using: decoder, label: "blurbs")

        return GeneratedMetadata(
            title: meta.title,
            subtitle: meta.subtitle,
            descriptionHTML: meta.description,
            chapters: chapters,
            keywords: meta.keywords,
            blurbs: blurbs
        )
    }

    // MARK: - Private

    private func decodeOrThrow<T: Decodable>(
        _ type: T.Type,
        from text: String,
        using decoder: JSONDecoder,
        label: String
    ) throws -> T {
        let cleaned = Self.stripCodeFences(text)
        guard let data = cleaned.data(using: .utf8) else {
            throw PodedgeError.llmFailed(reason: "Invalid UTF-8 in \(label) response")
        }
        do {
            return try decoder.decode(type, from: data)
        } catch {
            throw PodedgeError.llmFailed(reason: "Failed to decode \(label) JSON: \(error.localizedDescription)")
        }
    }

    /// Strips leading/trailing whitespace and markdown code fences from LLM output.
    static func stripCodeFences(_ text: String) -> String {
        var s = text.trimmingCharacters(in: .whitespacesAndNewlines)
        if s.hasPrefix("```json") {
            s = String(s.dropFirst(7))
        } else if s.hasPrefix("```") {
            s = String(s.dropFirst(3))
        }
        if s.hasSuffix("```") {
            s = String(s.dropLast(3))
        }
        return s.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    // MARK: - JSON Schemas

    static let metadataSchema = """
    {
      "type": "object",
      "properties": {
        "title": { "type": "string" },
        "subtitle": { "type": "string" },
        "description": { "type": "string" },
        "keywords": { "type": "array", "items": { "type": "string" } }
      },
      "required": ["title", "subtitle", "description", "keywords"]
    }
    """

    static let chaptersSchema = """
    {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "title": { "type": "string" },
          "startTime": { "type": "number" },
          "endTime": { "type": "number" }
        },
        "required": ["title", "startTime", "endTime"]
      }
    }
    """

    static let blurbsSchema = """
    {
      "type": "object",
      "properties": {
        "twitter": { "type": "string" },
        "linkedin": { "type": "string" },
        "mastodon": { "type": "string" }
      },
      "required": ["twitter", "linkedin", "mastodon"]
    }
    """
}
